box: jakirkham/centos_drmaa_conda
build:
    steps:
        - script:
            name: Ensure clean repo.
            code: |-
                git update-index -q --refresh

        - script:
            name: Build Conda Package.
            code: |-
                conda config --set show_channel_urls True
                conda config --add channels conda-forge
                source activate root
                conda update -y --all
                python setup.py bdist_conda

        - script:
            name: Create Conda Environment with package and dependencies.
            code: |-
                conda create -y --use-local -n testenv splauncher==$(python setup.py --version)
                source activate testenv

        - script:
            name: Install dependencies for cluster support.
            code: |-
                conda install -y drmaa

        - script:
            name: Install dependencies for building docs.
            code: |-
                conda install -y sphinx
                conda install -y cloud_sptheme

        - script:
            name: Install dependencies for profiling and monitoring coverage.
            code: |-
                echo "nose-timer 0.6.0" >> "$(conda info --root)/envs/testenv/conda-meta/pinned"
                conda install -y nose-timer
                conda install -y coverage
                conda install -y docstring-coverage
                conda install -y python-coveralls

        - script:
            name: Clean the environment.
            code: |-
                conda clean -tipsy

        - script:
            name: Test code.
            code: |-
                coverage erase
                python setup.py nosetests --with-timer

        - script:
            name: Test documentation.
            code: |-
                python setup.py build_sphinx
                docstring-coverage splauncher | tee .docstring-coverage

    after-steps:
        - jakirkham/email-notify:
            from: alerts@wercker.com
            to: $TO_EMAIL
            username: $FROM_EMAIL
            password: $PASS
            host: smtp.gmail.com:587
